### ISSUE TITLE
Steam Overlay not working

### ISSUE THREAD

**Issue by realchickenblue** [toebeann/BepInEx.Subnautica#10]
As soon as any plugin is installed, the Steam overlay no longer works..
Even after removing the plugin, no overlay. If I then delete Bepinex and copy it again to the games directory, the Steam overlay works again.

**Comment by toebeann** [comment]
If this is the case, this would be an issue with bepinex itself, not with this pack which includes bepinex, so issue is best left with https://github.com/BepInEx/BepInEx

However, from some googling this is likely a temporary glitch that may or may not be caused by BepInEx itself as most people who have reported this in the past have later said "nevermind it works now"
